apiVersion: v1
kind: Service
metadata:
  name: restaurante-frances-svc
spec:
  type: LoadBalancer
  selector:
    app: restaurante-frances
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
